format="""\
  $time\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $package\
  $nodejs\
  $docker_context\
  $kubernetes\
  $line_break\
  $character\
  """

[aws]
disabled = true

[kubernetes]
disabled = false

[time]
disabled = false
